name: Book new classes

on:
  schedule:
    - cron: '59 04 * * *' # runs at 04:59 UTC everyday which is 17:59 in NZDT
    - cron: '59 16 * * *' # runs at 16:59 UTC everyday which is 05:59 in NZDT
  workflow_dispatch:

jobs:
  book-classes:
    runs-on: ubuntu-latest
    steps:
      # This step allows the workflow to access script sin the repo
      - name: Checkout Code
        uses: actions/checkout@v2

      # This step set ups python in the virtual machine
      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install packages
      - name: Install Requirements
        run: pip install -r requirements.txt

      # This step sets the timezone
      - name: Set timezone to New Zealand
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Pacific/Auckland"

      # This step will execute the booking script in the virtual machine
      - name: Execute booking script
        working-directory: .

        env:
          # Set up username/password from GitHub secrets so they can be accessed.
          AB_USERNAME: ${{ secrets.USERNAME }}
          AB_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          # Run script to book new classes.
          python ./auto_book $AB_USERNAME $AB_PASSWORD --random_delay --calendar_notification

      # These next two steps commit files changes to the repository.
      # 'diff-index --quiet HEAD' is used in case there are no changes to the calendar files
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Update calendar' -a
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
